### ISSUE TITLE
Some improve points maybe helpful

### ISSUE THREAD

**Issue by ymfsing** [SystemCrafters/guix-installer#20]
1. Add sha256sum in build.yaml and echo to release-notes.md 

``` yaml
sha256sum ./guix-installer-$RELEASE_TAG.iso > ./guix-installer-$RELEASE_TAG.iso.sha256sum
echo "SHA256_ISO=$(cat ./guix-installer-$RELEASE_TAG.iso.sha256sum)" >> $GITHUB_ENV

echo $'SHA256 Checksums:\r\n\r\n```\r\n' >> release-notes.md
cat ./guix-installer-$RELEASE_TAG.iso.sha256sum >> release-notes.md
echo $'\r\n```' >> release-notes.md   
```

2. Add GitHub action dev-drprasad/delete-older-releases@v0.2.0 for deleting older releases

``` yaml
- name: Remove old release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 7
          delete_tags: true
```

3. Add nongnu substitute for descreasing build time when add linux, this idea comes from [starmun-0010 / guix-installer](https://github.com/starmun-0010/guix-installer) .
